#!/usr/bin/env python3
"""
vectors.json → vectors.h

C 侧不解析 JSON（避免为了测试引入 200 行 JSON 解析器），
改为在构建时把黄金向量降级成 C 数组。

这样 vectors.json 仍是唯一真相源，而 C 测试只依赖生成的中间头文件。

用法：
    python gen_header.py vectors.json > build/vectors.h
"""

import json
import sys


def cstr(s: str) -> str:
    """把 Python 字符串转成安全的 C 字符串字面量"""
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main() -> int:
    if len(sys.argv) < 2:
        print("usage: gen_header.py vectors.json", file=sys.stderr)
        return 2

    with open(sys.argv[1], "r", encoding="utf-8") as fp:
        d = json.load(fp)

    out = []
    w = out.append

    w("/* AUTO-GENERATED by proto/tests/gen_header.py -- DO NOT EDIT */")
    w("/* Source of truth: proto/tests/vectors.json */")
    w("#ifndef SCOPE_TEST_VECTORS_H")
    w("#define SCOPE_TEST_VECTORS_H")
    w("")
    w("#include <stdint.h>")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    uint16_t    cmd;")
    w("    uint8_t     flags;")
    w("    uint16_t    seq;")
    w("    const char *payload_hex;")
    w("    const char *frame_hex;")
    w("} vec_frame_t;")
    w("")
    w("typedef struct {")
    w("    const char *name;")
    w("    const char *stream_hex;")
    w("    int         split_at;      /* 0 = 一次性喂入 */")
    w("    const char *expect_cmd;    /* 逗号分隔的期望命令码序列 */")
    w("    const char *expect_seq;")
    w("    const char *expect_flags;")
    w("    const char *expect_payload;")
    w("    uint32_t    expect_crc_err;")
    w("    uint32_t    expect_dropped;")
    w("} vec_parser_t;")
    w("")
    w("typedef struct {")
    w("    uint16_t s0;")
    w("    uint16_t s1;")
    w("    const char *bytes_hex;")
    w("} vec_pack12_t;")
    w("")
    w("#define VEC_CRC_INPUT      %s" % cstr(d["crc_check"]["input_ascii"]))
    w("#define VEC_CRC_EXPECTED   ((uint16_t)0x%04X)" % d["crc_check"]["expected"])
    w("#define VEC_PROTO_VER      ((uint8_t)0x%02X)" % d["proto_ver"])
    w("")

    # ── frames ────────────────────────────────────────────────────
    w(f"#define VEC_FRAME_COUNT {len(d['frames'])}")
    w("static const vec_frame_t VEC_FRAMES[] = {")
    for f in d["frames"]:
        w("    {%s, 0x%04X, 0x%02X, %d, %s, %s}," % (
            cstr(f["name"]), f["cmd"], f["flags"], f["seq"],
            cstr(f["payload_hex"]), cstr(f["frame_hex"])))
    w("};")
    w("")

    # ── pack12 ────────────────────────────────────────────────────
    w(f"#define VEC_PACK12_COUNT {len(d['pack12'])}")
    w("static const vec_pack12_t VEC_PACK12[] = {")
    for p in d["pack12"]:
        w("    {0x%03X, 0x%03X, %s}," % (p["s0"], p["s1"], cstr(p["bytes_hex"])))
    w("};")
    w("")

    # ── parser ────────────────────────────────────────────────────
    w(f"#define VEC_PARSER_COUNT {len(d['parser'])}")
    w("static const vec_parser_t VEC_PARSER[] = {")
    for c in d["parser"]:
        cmds = ",".join(str(e["cmd"]) for e in c["expect_ok"])
        seqs = ",".join(str(e["seq"]) for e in c["expect_ok"])
        flags = ",".join(str(e["flags"]) for e in c["expect_ok"])
        pls = "|".join(e["payload_hex"] for e in c["expect_ok"])
        w("    {%s, %s, %d, %s, %s, %s, %s, %d, %d}," % (
            cstr(c["name"]), cstr(c["stream_hex"]), c.get("split_at", 0),
            cstr(cmds), cstr(seqs), cstr(flags), cstr(pls),
            c["expect_crc_err"], c["expect_dropped"]))
    w("};")
    w("")

    # ── state matrix ──────────────────────────────────────────────
    cmd_ids = [int(k) for k in d["state_matrix"][0]["allowed"].keys()]
    w(f"#define VEC_STATE_CMD_COUNT {len(cmd_ids)}")
    w("static const uint16_t VEC_STATE_CMDS[] = {")
    w("    " + ", ".join("0x%04X" % c for c in cmd_ids))
    w("};")
    w("static const uint8_t VEC_STATE_EXPECT[5][%d] = {" % len(cmd_ids))
    for row in d["state_matrix"]:
        vals = ",".join("1" if row["allowed"][str(c)] else "0" for c in cmd_ids)
        w("    {%s},   /* state %d */" % (vals, row["state"]))
    w("};")
    w("")

    w("#endif /* SCOPE_TEST_VECTORS_H */")

    sys.stdout.write("\n".join(out) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
